language: python
sudo: false
python:
  - 2.7
script:
  - pip install coveralls
  - python setup.py develop
  - coverage run setup.py test
after_success:
  - coveralls
deploy:
  provider: pypi
  user: Kaniabi
  on:
    tags: true
    repository: zerotk/clikit
  password:
    secure: IuoPa7GxyjoNJlRU+8p0vT90sb5D2m3LitBtHPlwKXz77bI5lndSJokX3yNGG7sPL8gBTKxxYhgpIPd3Pv7pSSXwI5N/r+jDivHvMEOmo54j8Df68I4WynZfGHdFEX/FH16MUsLstvtRQmznijVsXi5PCexQIJEJk8/h3E+wkBu8qSVEdJnkgCxAee5LaXZPdRtea7aQ/dDDimCoCiVAH8/SEizAuDjTCV+4MgwgXXxTAuyogCua9lCNKD+ge/YUMOtgzEMO5RaizMBoxH7rMRHD6sxSZZDl1zSJ8lRgSXevx7SWv3+/1ijELh94Cg7c9sfDOeZ/SAFb7k21/1HHCs1PLSjYrRV+LUe0DcECwgP3mYRw6bX+0/o5l//t+RYD+lU9Qzzswy7EM3wbTb9kWj35ui/GLlDJ5Yw6a8rP1bG+iMNn4NN3tMQvbe56dJJ/lWGrUcftGnh5nNDhhsaI4T/Uv7f1lNjUI1tqlXyT2CkMmEIQHmfgcQbm9b1smC4K6oT6s1MEM4LBRPCsLNKnwWqJnNbmfqZ+uYN5ZIAIjmWay+M93+qKrmtwMjICVjDOjuIll5ZCzErLViabgaJ5BymbPuBTfiZbMSQLyAqM++Hf7zFBq3QM7dCn9jaS3CB74xHwqaAt7xPpZNjVdN/vxWW+236Xqxglf8fVFoZhtv0=
